version: '3'

services:
  pythonweb:
    build: .
    container_name: pythonweb
    ports:
      - 8000:5000

  mysqlserver:
    image: mysql/mysql-server
    container_name: mysqlserver
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: