version: '3'

services:
  myshop-api:
    build: ./myshop_csproj
    container_name: myshop-api
    ports:
      - 8000:80
    networks:
      - myshop_net

  myshop-db:
    image: mysql
    container_name: myshop-db
    environment:
      MYSQL_USER: webapi_user
      MYSQL_PASSWORD: webapi_pw
      MYSQL_ROOT_PASSWORD: webapi_pw
      MYSQL_DATABASE: MyShopDB
    volumes:
      - ./mysqldata:/var/lib/mysql
    networks:
      - myshop_net


  myshop-migration:
    build: 
      context: ./myshop_csproj
      dockerfile: Dockerfile.migrations
    container_name: myshop-migrations
    tty: true
    networks:
      - myshop_net

networks: 
  myshop_net:


    